version: "3.9"

services:
  api:
    image: node:12-alpine
    command: sh -c "yarn development"
    volumes:
      - ./:/app
    working_dir: /app
    build: .
    ports:
      - "5000:5000"
  db: 
    container_name: 'postgre-container'
    image: postgres:10.5
    environment:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_PORT
        - POSTGRES_DB
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: "on-failure"
    healthcheck:
      test: ["CMD", "psql", "${POSTGRES_DB}", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

